services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "${EXTERNAL_PROXY_PORT}:80"
    volumes:
      - ./dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - web
      - file-server

  api:
    image: ghcr.io/ph-mold/ph-mold-server:${IMAGE_TAG}
    expose:
      - "3001"
    volumes:
      - ./dev/contents:/app/contents
    environment:
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}
      - DB_HOST=${DOCKER_DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}

  web:
    image: ghcr.io/ph-mold/ph-mold-web:${IMAGE_TAG}
    expose:
      - "3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_FILE_SERVER_BASE_URL=${NEXT_PUBLIC_FILE_SERVER_BASE_URL}

  file-server:
    image: nginx:alpine
    volumes:
      - ./dev/contents:/usr/share/nginx/html:ro
      - ./dev/nginx/file-server.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_CHARSET=utf8mb4
      - TZ=Asia/Seoul
    ports:
      - "${EXTERNAL_DB_PORT}:3306"
    volumes:
      - ./dev/db/data/mysql-data:/var/lib/mysql
      - ./dev/db/my.cnf:/etc/mysql/conf.d/my.cnf
