services:
  nginx-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "${EXTERNAL_PROXY_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - web
      - file-server

  api:
    image: ghcr.io/ph-mold/ph-mold-server:233ba22a49e1fb6248fb8558581006c2edc4cb64
    restart: always
    expose:
      - "3001"
    volumes:
      - ./contents:/app/contents
    environment:
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}
      - DOCKER_DB_HOST=${DOCKER_DB_HOST}
      - DB_HOST=${DOCKER_DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}

  web:
    image: ghcr.io/ph-mold/ph-mold-web:3a1ef883606b8cb3a57fa1c17339a21728588d3a
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_FILE_SERVER_BASE_URL=${NEXT_PUBLIC_FILE_SERVER_BASE_URL}

  file-server:
    image: nginx:alpine
    restart: always
    volumes:
      - ./contents:/usr/share/nginx/html:ro
      - ./nginx/file-server.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_CHARSET=utf8mb4
      - TZ=Asia/Seoul
    ports:
      - "${EXTERNAL_DB_PORT}:3306"
    volumes:
      - ./db/data/mysql-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
